output_audio_path: &out_audio_path output/audio_tts.wav
output_video_path: &out_video_path output/rendered_video.mp4

video_server: pexel

script_generator:
  video_time_length: 60
  words_per_minute: 210
  script_generation_prompt_path: config/script_generation_prompt.txt
  model_name: gpt-4o-mini

caption_generator:
  whisper_model_size: base
  max_caption_size: 15
  language: vi
  consider_punctuation: false
  srt_file_path: output/captions.srt # Can be None

keyword_generator:
  model_name: gpt-4o-mini
  temperature: 1.0
  video_search_keyword_prompt_path: config/video_search_keyword_prompt.txt

video_search:
  url: "https://api.pexels.com/videos/search"
  per_page: 15
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  target_duration: 15
  video_width: 1080
  video_height: 1920

video_composer:
  output_video_path: *out_video_path
  font_path: "font/Neue-Einstellung-Bold.ttf"
  font_size: 120
  text_color: "white"
  stroke_width: 4
  stroke_color: "black"
  text_position: ["center", 1200]
  video_codec: "libx264"
  audio_codec: "aac"
  fps: 25
  preset: "veryfast"

audio_generator:
  voice: "vi-VN-NamMinhNeural" # vi-VN-HoaiMyNeural # vi-VN-NamMinhNeural
  output_audio_path: *out_audio_path

description_generator:
  model_name: gpt-4o-mini
  description_prompt_path: config/video_description_prompt.txt
  output_description_path: output/description.txt
