name: Auto TikTok Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
      PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use Node.js v18 for compatibility

      - name: Install system dependencies for Playwright
        run: |
          sudo apt update
          sudo apt install -y \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxi6 \
            libxtst6 \
            libnss3 \
            libcups2 \
            libxss1 \
            libxrandr2 \
            libasound2 \
            libpangocairo-1.0-0 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            ffmpeg \
            make \
            build-essential

      - name: Install Node.js dependencies
        run: |
          cd src/tiktok_uploader/tiktok-signature
          npm install
          npx playwright install chromium

      - name: Install Python dependencies
        run: |
          make install


      - name: Run scripts test
        run: python src/script/script_generator.py

      - name: Run descripton generator test
        run: python src/script/description_generator.py
        
      - name: Run caption_generator test
        run: python src/captions/timed_captions_generator.py

      - name: Run keyword_generator test
        run: python src/video/video_search_query_generator.py

      - name: Run crawl data test
        run: python src/script/crawl_data.py

      # - name: Run image_text_matching test
      #   run: python src/video/image_text_matching.py

      # - name: Run video_urls_search test
      #   run: python src/video/background_video_generator.py
      
      # - name: Run audio_generator test
      #   run: python src/audio_generator.py


